# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jpmccfg23

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jpmccfgregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_80abc4f768d94c1aa564d347457183fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2d7b86d9ea234062afa9c069364644ec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jpmccfgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_80abc4f768d94c1aa564d347457183fc }}/jpmccfgregistry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jpmccfg23'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ac53abad864449f2a180a4df0a7bc029 }}
        images: 'jpmccfgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_80abc4f768d94c1aa564d347457183fc }}/jpmccfgregistry:${{ github.sha }}'